/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char content[7999];
	int ID;
};
typedef struct message message;

struct response {
	char content[7999];
	int status_code;
};
typedef struct response response;

#define RPC_PROG 0x20000001
#define RPC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define put 1
extern  int * put_1(struct message *, CLIENT *);
extern  int * put_1_svc(struct message *, struct svc_req *);
#define get 2
extern  struct response * get_1(int *, CLIENT *);
extern  struct response * get_1_svc(int *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define put 1
extern  int * put_1();
extern  int * put_1_svc();
#define get 2
extern  struct response * get_1();
extern  struct response * get_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);
extern  bool_t xdr_response (XDR *, response*);

#else /* K&R C */
extern bool_t xdr_message ();
extern bool_t xdr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
