/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

void _funcget();
void _funcput();

CLIENT *clnt;
char *host;

int main (int argc, char *argv[])
{
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	if ((clnt = clnt_create(host, RPC_PROG, RPC_VER, "tcp")) == (CLIENT*)NULL) {
		clnt_pcreateerror(host);
		exit(EXIT_FAILURE);
	}

	struct message test;
	strcpy(test.content, "hello");
	test.ID = 7907;
	printf("put is here\n");
	put_1(&test, clnt);

	get_1(10987, clnt);


exit (0);
}
