/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include "rpc.h"

char *current_local_time();
int generate_num();
int count = 0;

struct message messages[100] = {{"", 1}};

int *put_1_svc(struct message *argp, struct svc_req *rqstp) {
	int client_id = argp->ID;
	printf("Server had a put() request from client %d at current local time: %s.\n", client_id, current_local_time());
	static int result;

	if (argp->content == NULL) {
		result = -1;
		return &result;
	}

	messages[count].ID = client_id;
	strcpy(messages[count].content, argp->content);
	printf("For Client %d, put message: %s, random index: %d.\n\n", messages[count].ID, messages[count].content, count);

	count++;
	result = 0;
	return &result;
}

struct response *get_1_svc(int *argp, struct svc_req *rqstp) {
	int client_id = *argp;
	printf("Server had a get() request from client %d at current local time: %s.\n", client_id, current_local_time());
	static struct response result;
	int randomindex = generate_num();

	// while (messages[randomindex].ID == client_id) {
	// 	randomindex = generate_num()%count;
	// }

	printf("Index %d message: %s\n", randomindex, messages[randomindex].content);

	// if (strcmp(messages[randomindex].content, "")) {
	// 	printf("empty message %d\n", -1);
	// 	result.status_code = -1;
	// 	strcpy(result.content, "");
	// } else {
	// 	printf("has message %d\n", 0);
	// 	result.status_code = 0;
	// 	strcpy(result.content, messages[randomindex].content);
	// }

	result.status_code = 0;
	strcpy(result.content, messages[randomindex].content);

	return &result;
}

char *current_local_time() {
	time_t rawtime;
	time (&rawtime);
	char *current_time = ctime(&rawtime);
	return current_time;
}

int generate_num() {
	srand(time(NULL));
	int r = rand()%count;
	return r;
}
